architecture:
  arch_type: googlenet
  spec:
    num_classes: 100
    output_0_dropout: 0.7
    output_1_dropout: 0.7
    output_2_dropout: 0.4

dataset:
  name: cifar_100
  options:
    batch_size: 128
    normalise: true
    target_shape:
      - 48
      - 48

training:
  epochs: 200
  optimiser:
    type: adam
    spec:
      learning_rate: 0.0001
  losses:
    - categorical_crossentropy
    - categorical_crossentropy
    - categorical_crossentropy
  loss_weights: null
  metrics: null

wandb_project: "GH Keras Models"
