architecture:
  arch_type: mlp
  spec:
    hidden_sizes:
      - 16
      - 8
    output_size: 3
    hidden_activation: relu
    output_activation: sigmoid

dataset:
  name: iris
  options:
    batch_size: 8
    normalise: true

training:
  epochs: 200
  optimiser:
    type: sgd
    spec:
      learning_rate: 0.001
  losses:
    - categorical_crossentropy
  loss_weights: null
  metrics:
    - accuracy
    - precision
    - recall
  val_split: 0.2

wandb:
  project: "keras-models"
  name: "mlp_iris"
