architecture:
  arch_type: mlp
  spec:
    hidden_sizes:
      - 16
      - 8
    output_size: 3
    hidden_activation: sigmoid
    output_activation: sigmoid

dataset:
  name: iris
  options:
    batch_size: 8
    normalise: true

training:
  epochs: 200
  optimiser:
    type: sgd
    spec:
      learning_rate: 0.01
  losses:
    - categorical_crossentropy
  loss_weights: null
  metrics: null
  val_split: 0.2

wandb_project: "GH Keras Models"
